<?xml version="1.0" encoding="utf-8"?><Database Name="bazaSzkola" Class="bazaPolaczenieDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\Dom\Documents\bazaSzkola.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="Dziennik.Properties.Settings" SettingsPropertyName="bazaSzkolaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.adresy" Member="adresies">
    <Type Name="adresy">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ulica" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="nrDomu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nrMieszkania" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="miejscowosc" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="kodPocztowy" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="adresy_osoby" Member="osobies" ThisKey="id" OtherKey="idAdresu" Type="osoby" />
    </Type>
  </Table>
  <Table Name="dbo.uwagi" Member="uwagis">
    <Type Name="uwagi">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idUcznia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idNauczyciela" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tresc" Type="System.String" DbType="NChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="nauczyciele_uwagi" Member="nauczyciele" ThisKey="idNauczyciela" OtherKey="Id" Type="nauczyciele" IsForeignKey="true" />
      <Association Name="uczniowie_uwagi" Member="uczniowie" ThisKey="idUcznia" OtherKey="Id" Type="uczniowie" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.klasy" Member="klasies">
    <Type Name="klasy">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idWychowawcy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idUcznia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="oznaczenie" Type="System.String" DbType="NChar(3)" CanBeNull="true" />
      <Column Name="rokZalozenia" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="rokZakonczenia" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="nauczyciele_klasy" Member="nauczyciele" ThisKey="idWychowawcy" OtherKey="Id" Type="nauczyciele" IsForeignKey="true" />
      <Association Name="uczniowie_klasy" Member="uczniowie" ThisKey="idUcznia" OtherKey="Id" Type="uczniowie" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.nauczyciele" Member="nauczycieles">
    <Type Name="nauczyciele">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idOsoby" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="nauczyciele_uwagi" Member="uwagis" ThisKey="Id" OtherKey="idNauczyciela" Type="uwagi" />
      <Association Name="nauczyciele_klasy" Member="klasies" ThisKey="Id" OtherKey="idWychowawcy" Type="klasy" />
      <Association Name="nauczyciele_oceny" Member="ocenies" ThisKey="Id" OtherKey="idNauczyciela" Type="oceny" />
      <Association Name="nauczyciele_przedmioty" Member="przedmioties" ThisKey="Id" OtherKey="idNauczyciela" Type="przedmioty" />
      <Association Name="osoby_nauczyciele" Member="osoby" ThisKey="idOsoby" OtherKey="Id" Type="osoby" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.oceny" Member="ocenies">
    <Type Name="oceny">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idUcznia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idNauczyciela" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idPrzedmiotu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="komentarz" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="dataOtrzymania" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="nauczyciele_oceny" Member="nauczyciele" ThisKey="idNauczyciela" OtherKey="Id" Type="nauczyciele" IsForeignKey="true" />
      <Association Name="przedmioty_oceny" Member="przedmioty" ThisKey="idPrzedmiotu" OtherKey="id" Type="przedmioty" IsForeignKey="true" />
      <Association Name="uczniowie_oceny" Member="uczniowie" ThisKey="idUcznia" OtherKey="Id" Type="uczniowie" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.opiekunowie" Member="opiekunowies">
    <Type Name="opiekunowie">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idOsoby" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="opiekunowie_uczniowie" Member="uczniowies" ThisKey="Id" OtherKey="idOpiekuna" Type="uczniowie" />
      <Association Name="osoby_opiekunowie" Member="osoby" ThisKey="idOsoby" OtherKey="Id" Type="osoby" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.osoby" Member="osobies">
    <Type Name="osoby">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="imie" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="drugieImie" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="naziwsko" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PESEL" Type="System.String" DbType="NChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="dataUrodzenia" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="telefon" Type="System.String" DbType="NChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="idAdresu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="login" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="haslo" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="osoby_nauczyciele" Member="nauczycieles" ThisKey="Id" OtherKey="idOsoby" Type="nauczyciele" />
      <Association Name="osoby_opiekunowie" Member="opiekunowies" ThisKey="Id" OtherKey="idOsoby" Type="opiekunowie" />
      <Association Name="osoby_uczniowie" Member="uczniowies" ThisKey="Id" OtherKey="idOsoby" Type="uczniowie" />
      <Association Name="adresy_osoby" Member="adresy" ThisKey="idAdresu" OtherKey="id" Type="adresy" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.przedmioty" Member="przedmioties">
    <Type Name="przedmioty">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nazwa" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="skrot" Type="System.String" DbType="NChar(5)" CanBeNull="true" />
      <Column Name="idNauczyciela" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="przedmioty_oceny" Member="ocenies" ThisKey="id" OtherKey="idPrzedmiotu" Type="oceny" />
      <Association Name="nauczyciele_przedmioty" Member="nauczyciele" ThisKey="idNauczyciela" OtherKey="Id" Type="nauczyciele" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.uczniowie" Member="uczniowies">
    <Type Name="uczniowie">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idOsoby" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idOpiekuna" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idAdresu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="uczniowie_uwagi" Member="uwagis" ThisKey="Id" OtherKey="idUcznia" Type="uwagi" />
      <Association Name="uczniowie_klasy" Member="klasies" ThisKey="Id" OtherKey="idUcznia" Type="klasy" />
      <Association Name="uczniowie_oceny" Member="ocenies" ThisKey="Id" OtherKey="idUcznia" Type="oceny" />
      <Association Name="opiekunowie_uczniowie" Member="opiekunowie" ThisKey="idOpiekuna" OtherKey="Id" Type="opiekunowie" IsForeignKey="true" />
      <Association Name="osoby_uczniowie" Member="osoby" ThisKey="idOsoby" OtherKey="Id" Type="osoby" IsForeignKey="true" />
    </Type>
  </Table>
</Database>